apiVersion: v1
kind: Service
metadata:
  name: sample-api
  namespace: workshop-o11y
  labels:
    app: sample-api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: sample-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
  namespace: workshop-o11y
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: app
          image: sample-api:workshop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.workshop-o11y.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              value: sample-api
            - name: OTEL_TRACES_SAMPLER
              value: parentbased_traceidratio
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.5"
            - name: HIGH_CARD_ENTITIES
              value: "0"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
