# Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one or more contributor license agreements.
# SPDX-License-Identifier: Elastic-2.0

events {}

http {
  server {
    listen 8080;
    server_name _;

    location / {
      default_type text/plain;
      return 200 "nginx demo\n";
    }

    location /stub_status {
      stub_status;
      access_log off;
      allow all;
    }
  }
}
