events {}

http {
  server {
    listen 8080;
    server_name _;

    location / {
      default_type text/plain;
      return 200 "nginx demo\n";
    }

    location /stub_status {
      stub_status;
      access_log off;
      allow all;
    }
  }
}
